### ISSUE TITLE
Request for support: Reset behavior and multiplayer state

### ISSUE THREAD

**Issue by cwatsonc** [boardgameio/boardgame.io#1033]
I have been observing unusual behavior on the debugger:main:reset() functionality that seems to leave connected clients with an inconsistent state. 

Q: what is the expected behavior of reset() on connected clients?

see the behavior in [this video at 8:00](https://vimeo.com/646379976/3927488b0b) the preamble establishes an inconsistent state and reset is invoked.  The invoking client immediately changes to expected state consistent with client preemptive updates -- the alternate client doesn't update and a refresh by invoker reverts to pre-invocation state.

@delucis

**Comment by delucis** [comment]
@cwatsonc The debug panel controls are only really designed for local use, so it won’t work in multiplayer contexts. We should probably actually state that somewhere. Dispatching moves via the debug panel or inspecting state should be OK, but reset and the save/restore functionality will likely break multiplayer client state.

**Comment by cwatsonc** [comment]
Maybe a thin wrapper could be made available?  Most definitely a warning should be issued when used in that context -- thanks I'm okay with closing this issue if the corrective measures are somehow tracked -- else can we convert this issue to a feature request based on your guidance?

**Comment by delucis** [comment]
Not sure what you mean by wrapper in this context, but this would actually be a complex undertaking. Currently the multiplayer implementation has no concept of reset actions at all because there would then need to be a way to authenticate who can reset when (obviously the server shouldn't allow people to reset mid game in normal circumstances). So to get that working, first the server logic would need to support a bunch of things that aren't actually needed for gameplay, which it's hard to justify spending too much energy on.

Instead I'd recommend debugging/testing *without* multiplayer for full access to reset etc. Then once you're happy with behaviour, add multiplayer to double check if things still work as expected.

We could definitely look into hiding the reset controls for multiplayer clients. That shouldn't be too much of a lift.

**Comment by cwatsonc** [comment]
@delucis in my case I was trying to reset the game state to a previous phase.  It was hard to orchestrate with any of the moves and reset was thought to be a cure... thanks for correcting.  I think if the game had an abandonDeal move I could create the same effect -- as you mentioned this should not be allowed spuriously in game play -- my thought being that it would be a developer switch.  I'm running games in a long play scenario where a game will run indefinitely--something FBG currently "supports" by retaining links to the instance -- my goal is to be able to support tournament play where players will come and go at will to rejoin play when the players are present -- in that mode the identity of the players may not be known at inception and will be added adhoc -- something I don't know if FBG will ever support -- I get a lot of indications that I'll be jailed forever in dev mode but I have a lot of learning to do and for now it works as a well supported community. Thanks for your help -- I think bgio is had a major impact on my progress and you've always been gracious with your advice and mentoring -- cheers cw

**Comment by delucis** [comment]
Glad to help. I’ll close this for now and I’ve open #1034 to track hiding/disabling those controls in scenarios where they won’t actually work.
