### ISSUE TITLE
set next player in endTurn event

### ISSUE THREAD

**Issue by JuanRamino** [boardgameio/boardgame.io#1056]
Hi,

I'm trying to set the next player in endTurn event but it does not work.
In my game (2 players) who win the hand should start the next one.

`ctx.events.endTurn({ next: winner.playerID });`

should do the job but it does not work.  

`ctx.events.endTurn({ next: '1' }); // does not work`
`ctx.events.endTurn({ next: '3' }); // player 3 does't exists but i get no error`

I always get the other player in the next turn.

What could be wrong? Thanks

https://codesandbox.io/s/github/JuanRamino/briscola

**Comment by delucis** [comment]
Hi @JuanRamino!

I’m not able to reproduce that using a simple game:

https://codesandbox.io/s/endturn-next-test-f0xq2?file=/src/App.tsx

I _think_ the problem is that you are using `maxMoves` and that is ending the turn before `ctx.events.endTurn` has a chance to run. I would try without `maxMoves` to confirm that’s the issue. You’ll probably need to make sure your move always ends the turn though in that case, not only when the player won the hand.

An alternative approach would be to keep `maxMoves` and use a custom `turn.order.next` function to decide who the next player is instead of doing that inside the move.

**Comment by JuanRamino** [comment]
Hi @delucis and thanks for your help!

Removing _maxMoves_ and manually call _endTurn_ solve the issue

Good job!
