### ISSUE TITLE
Passing a move directly to an onClick handler in React causes circular dependency error in debug panel

### ISSUE THREAD

**Issue by mateomurphy** [boardgameio/boardgame.io#1122]
In my code I had a button setup like this:

```
<button onClick={moves.restHand}>Rest</button>
```

When I click on it and open the `Log` tab in the debug panel, I get the following error:

```
Unhandled Runtime Error
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLButtonElement'
    |     property '__reactFiber$i437dwsu9i' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
```

It works fine if I do:

```
const handleClick = () => {
    moves.restHand
}

<button onClick={handleClick}>Rest</button>
```

The error itself occurs in this line of code: https://github.com/boardgameio/boardgame.io/blob/main/src/client/debug/log/LogEvent.svelte#L15

**Comment by delucis** [comment]
Hi @mateomurphy! This is expected and not limited to the debug panel.

When you pass a move directly like that, the move will be called with the event object as its argument: `move(clickEvent)`.

These JS event objects are big and include all sorts of complex data including DOM node references so we can't serialise them to JSON to send to the server as we need to. (This technical detail could theoretically be skipped when running without a server, but in my opinion that be would a worse dev experience because you'd have click handlers that worked _until you tried adding a server_.)

Instead you need to make sure you wrap the move like you mention.

**Comment by mateomurphy** [comment]
Right, in hindsight this makes sense. It seems this could be handled better to avoid crashing the entire game though (if only via a `try/catch` block). Also, Is there a way to add types to the move functions?

**Comment by delucis** [comment]
You mean types so that `moves.foo()` knows what types of arguments it should receive based on your game?

It’s tricky to do. There’s some discussion and an experiment at achieving this in this thread: https://github.com/boardgameio/boardgame.io/discussions/903
