### ISSUE TITLE
`ctx.currentPlayer` is string

### ISSUE THREAD

**Issue by haoyangnz** [boardgameio/boardgame.io#457]
Is there any reason why `ctx.currentPlayer` is string `"0"` rather than `0`.

**Comment by nicolodavis** [comment]
This is mostly around for legacy reasons when it was once thought convenient to have a string so that it can be replaced by a player name.

However, the player names shouldn't really be stored as part of the game state, and they're stored in a separate metadata section now.  So, we don't really have a reason to keep playerID's as strings and they should be integers instead.

**Comment by haoyangnz** [comment]
@nicolodavis Is there a way for the game to access the `playerName` from lobby for `ctx.currentPlayer`?

**Comment by nicolodavis** [comment]
Yes, use the `gameMetadata` prop as documented [here](https://boardgame.io/documentation/#/api/Client).

**Comment by haoyangnz** [comment]
@nicolodavis Using `Lobby` instead of the regular `Client` I don't have `gameMetadata` in Board's prop. Is this a bug or am I doing something wrong?

**Comment by haoyangnz** [comment]
Oh I see this is fixed in #436 but not released yet.
