### ISSUE TITLE
endTurn inside onBegin doesn't work

### ISSUE THREAD

**Issue by nicolodavis** [boardgameio/boardgame.io#526]
```js
{
  turn: {
    onBegin: (G, ctx) => {
      if (ctx.turn < 10) ctx.events.endTurn();    // this is a no-op
    }
  }
}
```

This [check](https://github.com/nicolodavis/boardgame.io/blob/master/src/core/events.js#L49) prevents the `endTurn` because the `Events` class is attached at a point where the turn was 0 [here](https://github.com/nicolodavis/boardgame.io/blob/master/src/core/initialize.js#L36), but by the time the event is processed the turn is incremented to 1.

**Comment by delucis** [comment]
Won’t this actually impact `endTurn` in all `onBegin` hooks? I think the `Events` used in `onBegin` will always be instantiated in the previous turn during a game.

**Comment by Oliboy50** [comment]
I opened a somehow similar issue #558 

but I think my issue is more about this [check](https://github.com/nicolodavis/boardgame.io/blob/master/src/core/events.js#L58) instead

**Comment by Oliboy50** [comment]
BTW, these checks doesn't make sense to me:

```js
      // If the turn already ended some other way,
      // don't try to end the turn again.
      if (item.key === 'endTurn' && item.turn !== state.ctx.turn) {
        continue;
      }

      // If the phase already ended some other way,
      // don't try to end the phase again.
      if (
        (item.key === 'endPhase' || item.key === 'setPhase') &&
        item.phase !== state.ctx.phase
      ) {
        continue;
      }
```

I mean... instead of `item.turn !== state.ctx.turn`, it should be `item.turn === state.ctx.turn`, no?
And instead of `item.phase !== state.ctx.phase`, it should be `item.phase === state.ctx.phase`, no?

I think I've already spent too many hours [trying to migrate from 0.32 to 0.33](https://github.com/nicolodavis/boardgame.io/issues/558) now... 
I'll just give up on this new version until everything works as expected :'(

**Comment by delucis** [comment]
These checks do the following:

1. Are we processing an `endTurn`/`endPhase` etc. event?

2. If so, are we in the same turn/phase as we were when we started processing events?

3. If _not_, that means the original turn/phase has already been ended and we won’t process another end or set event. Because the processing of events involves iterating through a stack of events, we use `continue` to skip  next item in the stack.

They’re logically correct, but they do introduce various side effects as detailed in the original bug report.

**Comment by amishne** [comment]
Just to add my voice here: I have a phase in which turns are sometimes skipped and sometimes not, depending on the current player and the game state. Calling endTurn conditionally from onBegin makes intuitive sense to me, but from the response here it seems there's no way to make that happen. **Is there any work-around for this behavior**, i.e. any way to end the current turn immediately when a turn starts, before any moves occur?

The proposed solution in the linked bug - using endIf - doesn't seem to work for me, that turn's endIf is never called after the turn's onBegin.

The other proposed work-around, calculate the next player / phase in advance, is significantly more complicated in my user-case, not to mention it involves moving logic that rightfully belongs in a given phase into a previous phase.

**Comment by delucis** [comment]
This is the second such comment I’ve fielded in a couple of days and I feel like it would be good to improve the DX here. My understanding is (correct me if I’m wrong @nicolodavis) that the intention of preventing ending turns/phases more than once is to a) prevent infinite loops and b) to insulate users from game logic errors where say they call `endTurn` and `endIf` also returns `true` or `endTurn` is called multiple times.

We could still protect against infinite loops by setting an arbitrary threshold for max turn ends. The current logic (in [the flow reducer](https://github.com/boardgameio/boardgame.io/blob/5207be5823364a0107370ea8834f620a55131134/src/core/flow.ts#L478-L486) and [the events plugin](https://github.com/boardgameio/boardgame.io/blob/5207be5823364a0107370ea8834f620a55131134/src/plugins/events/events.ts#L80-L82)) effectively sets a limit of 1 turn ending per action. This could be increased to `2 * numPlayers` or a configurable large number instead.

Addressing b) is a bit trickier, although it is technically programmer error, so perhaps there is some heuristic that could be use to at least log warnings if it looks like someone is caling events repeatedly.
