### ISSUE TITLE
Debug UI buggy ....

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#670]
... in case of multiple clints on local master. 
![Screenshot 2020-05-06 at 11 05 53](https://user-images.githubusercontent.com/3854675/81160839-e6e13880-8f8a-11ea-9164-ac6f56eaca09.png)

When i click 'End Phase' it throws error `ERROR: player not active - playerID=[3]` 
This is becuase my table component is like this : 

```    
    <div id="table">
      <Client gameID="123" playerID="0" />
      <Client gameID="123" playerID="1" />
      <Client gameID="123" playerID="2" />
      <Client gameID="123" playerID="3" />
    </div>
```
When i change it to be 
```  
    <div id="table">
      <Client gameID="123" playerID="3" />
      <Client gameID="123" playerID="2" />
      <Client gameID="123" playerID="1" />
      <Client gameID="123" playerID="0" />
    </div>
```

Then it works, it first case i have to make few moves, and wait till 'activePlayer' and 'currentPlayer' is same. Whatever the difference between active and current is ( i dont se it yet ) it cant be like that ability to end phase depends on elements orders in DOM. Also when i click on 'End Phase' when it is allowed phase is not finished properly. `ctx.phase`shows updated value but, list of allowed moves is not updated, this is for sure related to https://github.com/nicolodavis/boardgame.io/issues/669

**Comment by delucis** [comment]
Hi @pociej — I think this bug is caused because when you instantiate multiple clients, you’re actually getting multiple debug panels. They’re on top of each other so you can’t really see this — the only slight visual hint is that the box-shadow is darker than usual.

You can see in your screenshot that with the `playerID` order 0, 1, 2, 3, there’s an orange box around the 3 indicating it’s the debug panel for player 3, switching the order to 3, 2, 1, 0, renders 0 last in the DOM and therefore now player 0 has the “top” debug panel.

We should probably try to see if there’s a way for us to detect multiple clients and only render one per master instead of one per client.

In the meantime, I would suggest debugging with just one board (you can switch the displayed player using the debug panel), and do multi-client tests once you can make moves/events from the board itself.

**Comment by nicolodavis** [comment]
> We should probably try to see if there’s a way for us to detect multiple clients and only render one per master instead of one per client.

I agree.
