### ISSUE TITLE
Support for mongo

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#677]
I see that in newest version Mongo is not supported anymore,  but in docs one can see 'Coming soon (used to be supported but is not in sync with the latest release).' Are you actively working on it? I need it as my games depends on Mongo and i want them to stick with mongo so if its not going to be pushed in next days, i would implement Mongo support and make PR. Or maybe there are some issues you have that caused this temporary remove of Mongo?

**Comment by delucis** [comment]
@pociej The general plan is to encourage third-party database packages rather than including them directly in this library. See [bgio-firebase](https://github.com/delucis/bgio-firebase) and [bgio-azure-storage](https://github.com/c-w/bgio-azure-storage) for examples. It’s hard for us to maintain them here if they’re not services we’re familiar with or are actively using, so this lets community members help out with their expertise. If you would like to work on a Mongo connector, let us know if you have any questions. A database connector should implement [the abstract `StorageAPI.Async` class](https://github.com/nicolodavis/boardgame.io/blob/26076ce86ab94d0bf473ef02d905060437c72b3c/src/server/db/base.ts#L49-L111).

**Comment by delucis** [comment]
Closing this in favour of the discussion in #6.
