### ISSUE TITLE
error loading react client 

### ISSUE THREAD

**Issue by jstacoder** [boardgameio/boardgame.io#766]
after 72ed5913 i cant load the react client:

```
Error: Function called outside component initialization
```

which traces back to svelte calling `get_current_component` after importing svelte in [src/client.js](https://github.com/boardgameio/boardgame.io/blob/72ed591310bec944cbb3b7eba458726b810b3a1d/src/client/client.ts#L9)

**Comment by delucis** [comment]
Thanks for the report! 72ed591 isn’t included in the latest release; are you installing from GitHub directly?

**Comment by delucis** [comment]
OK, I can reproduce this using 0.39.15, so I suspect this was actually introduced in 271aecd18bd14aa5a331d615a844762c22b94536, and likely not fixed by 72ed591. 

Reproduction: <https://codesandbox.io/s/test-bgio-latest-l8obj>

**Comment by delucis** [comment]
OK, I think the bug was caused when we moved `svelte` from `devDependencies` to `dependencies` (to make svelte’s type declarations available to boardgame.io users). Our Rollup config marks any direct dependency in package.json as external:

https://github.com/boardgameio/boardgame.io/blob/72ed591310bec944cbb3b7eba458726b810b3a1d/rollup.config.js#L20-L21

That led to the bundle including `import 'svelte'` statements, which it shouldn’t. In short `import 'svelte'` is there for Typescript, not for JS functionality, so shouldn’t be included in the bundle output. Running a few more local tests, and then I’ll open a PR to fix this.

**Comment by jakehsiao** [comment]
Oh I got this bug too.

**Comment by delucis** [comment]
@jakehsiao I’d recommend downgrading to `boardgame.io@0.39.14` for now. If you’re using Typescript, you may need to downgrade to `0.39.13` as there were some issues with the types in `0.39.14`.

**Comment by nicolodavis** [comment]
#767 is available in `0.39.16`, so you can try that.

**Comment by delucis** [comment]
Thanks @nicolodavis!
