### ISSUE TITLE
The move executed after any end turn or phase move does not show in opponent logs.

### ISSUE THREAD

**Issue by larry801** [boardgameio/boardgame.io#795]
Here is code sandbox to reproduce.

https://codesandbox.io/s/epic-ritchie-jxeo6?fontsize=14&hidenavigation=1&theme=dark

In the board of player 0
Press button 0 under "Order" Press button 3 under "Plan" the move plan is not shown in log
Then comment out line 24
```
client:false,
```
 in Game.js 
In the board of player 0
Press button 0 under "Order" Press button 3 under "Plan" the move plan is shown in log

**Comment by delucis** [comment]
Thanks for the bug report and reproduction! Here’s a stripped-down reproduction with one server-only move and one normal move: https://codesandbox.io/s/bgio-client-false-move-debug-ri7ed

Another key component to the bug seems to be that the server-only move triggers a turn end — if you disable the `moveLimit` in this example, it works as expected. Manual turn ends don’t trigger the bug either. It also only breaks after the first move. Will need some further investigation to figure out what’s going on!

**Comment by delucis** [comment]
Oh, and I’ve just noticed discrepancies between the logs for the two player clients, so that might be a hint where things are going wrong!

**Comment by larry801** [comment]
@delucis  thanks for your attention 
For now ,I can just disable moveLimit and add a dedicated endTurn move for workaround.

**Comment by larry801** [comment]
I tried dedicated end turn move in my game, and found that any move triggering turn or phase end can cause this bug, including a client move.

Here is a minimal reproduction based on yours.
https://codesandbox.io/s/bgio-end-turn-or-phase-move-debug-csh6w

* disable move limit as player 0,
* make an end turn or end phase client move as player 1
* make any move as player 0

The third move is only shown in the log of player 0.

**Comment by delucis** [comment]
@larry801 Thanks. I think it makes sense to see the bug here too. The reducer doesn’t update state on the client [if any plugin tells it not to](https://github.com/boardgameio/boardgame.io/blob/0062e5508f0e8f86c9bf9f60bd4da0c641b7e184/src/core/reducer.ts#L187-L192), which the events plugin does if it was used by a move. In effect, a move calling an event will always be a server move.

For your case, you may be able to use the event from the client directly (calling `props.events.endTurn` instead of `props.moves.clientEndTurn`), but obviously this bug still needs addressing more generally.

**Comment by delucis** [comment]
OK, I have a diagnosis for this!

When moves trigger a phase or turn end, the automatic event has an incremented `_stateID`, so when the client receives the next update (by an opponent), it ends up being filtered out here:

https://github.com/boardgameio/boardgame.io/blob/0062e5508f0e8f86c9bf9f60bd4da0c641b7e184/src/client/client.ts#L218-L222

For example, making a move could trigger log entries something like this:
- `{ action: { type: 'MAKE_MOVE' }, _stateID: 2 }`
- `{ action: { type: 'GAME_EVENT' }, _stateID: 3, automatic: true }`

The next move would trigger:
- `{ action: { type: 'MAKE_MOVE' }, _stateID: 3 }`
which will be filtered out because its `_stateID` is too low.

Need to figure out what the fix is. I suspect that the `automatic: true` events should share the `_stateID` with the moves, but need to check up where exactly that’s coming from.
