### ISSUE TITLE
Error: An immer producer returned a new value *and* modified its draft. Either return a new value *or* modify the draft

### ISSUE THREAD

**Issue by proach123** [boardgameio/boardgame.io#803]
I've been playing around with Async functions in my Game.js file. Right now I am building a card game similar to MTG and was trying to clean up my draw function with some async logic. I split my draw with a helper that would await for some of the draw initial logic to finish. However, when I made this change to an async function I got the error in the title. 'Error: An immer producer returned a new value *and* modified its draft. Either return a new value *or* modify the draft'.

Here is what my code looks like:

```js
async function Player0DrawCard(G, ctx, drawCount=1, firstDraw=1){
    if(G.player0Graveyard[0] == null && G.intialShuffle === true && G.player0Hand.length > 5     ){
        return INVALID_MOVE
    }
     if(G.player0Deck[0] == null){
        G.player0Deck = [...G.player0Graveyard]
        G.player0Graveyard = []
        G.player0Deck = [...ctx.random.Shuffle(G.player0Deck)]
        //deck gets replaced by graveyard then graveyard returns to an array then deck shuffles, then normal draw happens.
        //this works because boardgame.io handles the immutability behind the scenes and lets us do things like this to the G obj.
    }

    await draw0Helper(G,drawCount)

    if(firstDraw === 1){
        ctx.events.endStage()
    }
    ctx.events.setActivePlayers({ all: 'play', moveLimit: 1 });
}

draw0Helper(G,drawCount){
    let i = 0
    while(i < drawCount){
        if(G.player1Deck[0] != null){
            G.player0Hand.push(G.player0Deck[0])
            G.player0Deck.shift()
        }
        i++
    }
}
```

Sorry if this is a messy explanation. This is quite literally my first git hub issue report. I did some digging on the error that I'm getting with immer producer's and Redux and it seems like there is something on the reducer that needs to be changed with a void? Here is what I found: https://stackoverflow.com/questions/60806105/error-an-immer-producer-returned-a-new-value-and-modified-its-draft-either-r.`

Seems like something with the boardgame.io reducer needs to be changed. I'll work on a workaround in the meantime but help appreciated!

**Comment by delucis** [comment]
Hi @proach123! boardgame.io doesn’t support async functions in game logic, so that’s the basic explanation. Looking at the code you shared, you may be able to get away without them in any case: the `draw0Helper` function is not asynchronous so you don’t need to `await` it in `Player0DrawCard`, which in turn means that `Player0DrawCard` doesn’t need to be an `async` function:

```diff
- async function Player0DrawCard(G, ctx, drawCount=1, firstDraw=1){
+ function Player0DrawCard(G, ctx, drawCount = 1, firstDraw = 1) {
  // ...

- await draw0Helper(G,drawCount)
+ draw0Helper(G, drawCount);

  // ...
}
```

To explain the error message a little: we use Immer to enable simple immutable updates from your game code. There’s some [more detail on this in the documentation](https://boardgame.io/documentation/#/immutability). However, if your move is an `async` function, when your move function is called, instead of returning `undefined` or a new `G`, the function actually returns a Promise (even if it’s just a Promise that resolves to undefined as in your case). In your case, you are modifying `G` (the “draft”), but also returning a Promise, which Immer believes to be a “new value,” so it throws that error. Converting your function to avoid async/await should resolve your issue.

**Comment by proach123** [comment]
Thanks for the explanation! I'll close the issue and change my function around it was more of a test of concept than a necessary thing so I'm glad to know this now. Thanks again for your help!
