### ISSUE TITLE
Undo redo not reflected in log

### ISSUE THREAD

**Issue by larry801** [boardgameio/boardgame.io#820]
Here is a minimal reproduce
https://codesandbox.io/s/bgio-undo-redo-not-reflected-in-log-hcmdi

Make a move then undo.
Game state is rolled back. but log still presents

**Comment by delucis** [comment]
Thanks for the report — I can confirm this. The [reducer doesn’t currently modify the logs for undo/redo actions](https://github.com/boardgameio/boardgame.io/blob/master/src/core/reducer.ts#L240-L295). We could either try including logs in the undo/redo stacks so that they can be restored like the rest of the state, or we could add undo/redo entries to the logs, so that the logs track those too.
