### ISSUE TITLE
No validation for games created on demand (by master.onSync)

### ISSUE THREAD

**Issue by jojonas** [boardgameio/boardgame.io#847]
If the socket client (re)connects to a game that has not yet been created, `onSync` attempts to create a game on the fly (see https://github.com/boardgameio/boardgame.io/blob/6c4e94fa7369c41098ccf6747689e091d818cbbe/src/master/master.ts#L392), which directly calls `InitializeGame`. 

This is a completely different code path than the game creation via the REST API (https://github.com/boardgameio/boardgame.io/blob/d071e98c0868ea687d85168649e5d6302fb15229/src/server/api.ts#L128). For example, the REST API calls `validateSetupData` before calling `CreateGame` which then calls `InitializeGame`.

This results in `onSync` trying to create games with invalid values, rendering the validation useless.

In my case, this results in an error being thrown which in turn causes the entire server to die.

**Comment by delucis** [comment]
Thanks for the report @jojonas.

What do you think about wrapping this line in `try`/`catch`?

https://github.com/boardgameio/boardgame.io/blob/6c4e94fa7369c41098ccf6747689e091d818cbbe/src/master/master.ts#L395

If `InitializeGame` throws, we would return an `error` object from `onSync` (similar to when a player isn’t authorized) and protect the server from crashing.

**Comment by jojonas** [comment]
I feel like while wrapping this in `try ... catch` is part of the solution, we should work towards deduplicating the match setup code.

**Comment by delucis** [comment]
@jojonas Indeed, that would be better. I’m currently working on a PR that will introduce credentials/authentication to the sync event (addressing #840), but it might also make sense to allow `setupData` to be sent on sync like `numPlayers` and then call `validateSetupData` as part of the game creation flow. The signature should probably end up looking something like

```ts
onSync(
  matchID: string,
  playerID: string,
  credentials?: string,
  matchCreationOpts?: { numPlayers?: number; setupData?: any; },
): void
```

Does that sound more reasonable?

**Comment by jojonas** [comment]
Hi, sorry, I am just getting around on working on board games during my Christmas holidays. This implementation still looks like code duplication on the first glance. Maybe the server could just return a HTTP error if the match does not exist?

**Comment by delucis** [comment]
There could definitely be some duplication here — would be nice to limit that by factoring out to shared code. However, the master is not only used on the server, but also in some client contexts, which is why it needs to self-instantiate game state here rather than just erroring. (Historically some people have also used this with the server to avoid using a lobby at all. I’m not a fan of this pattern, which results in unsecured matches, but it is easy to use for some simple cases.)

Either way there should be protection here to avoid crashing servers like yours that aren’t expecting this on-demand usage.
