### ISSUE TITLE
Strange behaviour for setStage and setActivePlayers for Stage.NULL

### ISSUE THREAD

**Issue by evandroabukamel** [boardgameio/boardgame.io#848]
Hey guys, what's up? I have a question about using the Stage.NULL. In the docs it's said that players can become active but in no stage if we set them to Stage.NULL using `setActivePlayers`.

What I'm trying to achieve is to make all players to use a specific move from no stage but when they make some moves from specific stages they must exit that stage but still become active. So, I'm trying to keep all other players in the same state they are when players calls a move that should put themselves to Stage.NULL. Now, everybody receive a "player not active" error. So I try a few things:

**1. Using `setStage(Stage.NULL)` at the end of a move:** by doing this, the player was removed from `activePlayers` property, thus becoming inactive.

**2. Using `setActivePlayers([ctx.playerID])` at the end of a move:** by doing this, only that player becomes active in Stage.NULL and all other players are removed from `activePlayers` property.

So, am I doing something wrong or is there a bug in one of those functions?
What you suggest me to do? I was thinking of merge the current `ctx.activePlayers` with `setActivePlayers` parameter, but I think this is very risky. Don't know.

Thanks.

**Comment by delucis** [comment]
`setActivePlayers` overwrites the entire state, so yes, one way to set just one player, would be to spread the existing state in:

```js
function onMove(G, ctx) {
  ctx.events.setActivePlayers({
    value: {
      ...ctx.activePlayers,
      [ctx.playerID]: Stage.NULL,
    }
  });
}
```

That isn’t really risky, but `setActivePlayers` does reset move counts etc., which may be undesirable.

More importantly, `setStage(Stage.NULL)` should work. My guess would be there’s a check somewhere that does `if (arg)` instead of `if (arg || arg === Stage.NULL)`, probably these two:

https://github.com/boardgameio/boardgame.io/blob/5d34610064bf5ea6591c1633f4eba61e2ff8a8c5/src/core/flow.ts#L559-L567

Would you like to fix that and add a test for `setStage(Stage.NULL)`?

**Comment by evandroabukamel** [comment]
Sure, I'll do that, also tried that with a unit test and found that bug.

**Comment by evandroabukamel** [comment]
@delucis , can I solve #777 too? I believe I found it here and it's very simple to fix.

**Comment by delucis** [comment]
> can I solve #777 too?

I'm not sure I think #777 is so helpful either. We have to check that active players is empty quite often which would become something like `Object.keys(ctx.activePlayers).length === 0`, which is also not a great experience.
