### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by jakehsiao** [boardgameio/boardgame.io#875]
Does the server of boardgameio support serverless deployment? If it does not, do you have the plan for it?

**Comment by larry801** [comment]
As long as you do not store game state in memory or file, bgio server is actually stateless.
You can save game state in object storage service (such as firebase, Lean Cloud )with [custom adapter](https://boardgame.io/documentation/#/storage?id=writing-a-custom-adapter) to further adapt to server less deployment.

**Comment by delucis** [comment]
Because the main gameplay server relies on websockets, it needs a full server to run — I don’t know if there are services that provide some kind of “serverless” sockets. As @larry801 suggests, you could theoretically use something like Firestore’s real-time capabilities to keep two clients in sync directly from the browser, but it would be hard to do so securely, because at least with Firestore you’d need to rewrite all kinds of security rules essentially duplicating game validation logic.

A serverless approach that might work, could be to use a function service like AWS Lambda or Google Cloud Functions. Each of these services is different, so I’m not sure boardgame.io could support serverless functionality out of the box. Writing a serverless implementation to replace the socket.io gameplay server should be fairly do-able. You would need a function that runs the game master for the requested action and a client transport that sends actions to that endpoint instead of connecting to a websocket. Replicating the full Lobby API would probably require a lot of copy/paste at the moment, but perhaps there are ways to make the API logic more reusable for people who want to try this.

**Comment by delucis** [comment]
Closing this for now as serverless is not a particularly great fit for the boardgame.io architecture and we’re unlikely to invest time on this feature. Happy to reopen for discussion/PRs later.
