### ISSUE TITLE
npm run serve command fails on JSX

### ISSUE THREAD

**Issue by alexwoodsy** [boardgameio/boardgame.io#909]
For some reason I cannot the get the `node -r esm src/server.js`  script to run when setting up multiplayer functionality. My server.js file is identical to that in the documentation. I get the following error when it reaches the first JSX element in my game.

`> shed-online@0.0.0 serve C:\Users\alexw\Documents\programming projects\SHED-online
> node -r esm src/server.js

C:\...\SHED-online\src\game\Table.js:72
                <CardImage card={props.card} x={x} y={y} width={cardwidth} height={cardheight} rotation={rotation} fill={'blue'} shadowBlur={15} reverse={props.reverse} player={props.player} onClick={props.onClick} />
                ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shed-online@0.0.0 serve: `node -r esm src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shed-online@0.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

is this the same issue as mentioned in [this thread?](https://github.com/boardgameio/boardgame.io/discussions/902#discussion-2572587)
If anyone has any idea's please let me know.
Many thanks :)

**Comment by delucis** [comment]
@alexwoodsy I think the thread you linked is for a different issue, that thread is about Typescript rather than JSX.

I don’t think you should be including any JSX in the server code. What exactly are you importing in `server.js`?

If you check out this example from [the multiplayer tutorial](https://boardgame.io/documentation/#/multiplayer?id=setting-up-the-server), the `./Game` file being imported is plain JavaScript, separate from front-end code that could include JSX:

```js
// src/server.js
const { Server } = require('boardgame.io/server');
const { TicTacToe } = require('./Game');

const server = Server({ games: [TicTacToe] });

server.run(8000);
```

You can think about the structure a little like this:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBHW1wiR2FtZSBkZWZpbml0aW9uIChwbGFpbiBKUylcIl0gLS0-IFNbXCJTZXJ2ZXIgKHBsYWluIEpTKVwiXVxuICAgIEcgLS0-IENbXCJGcm9udC1lbmQgY29kZSAobWF5IGluY2x1ZGUgSlNYKVwiXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBHW1wiR2FtZSBkZWZpbml0aW9uIChwbGFpbiBKUylcIl0gLS0-IFNbXCJTZXJ2ZXIgKHBsYWluIEpTKVwiXVxuICAgIEcgLS0-IENbXCJGcm9udC1lbmQgY29kZSAobWF5IGluY2x1ZGUgSlNYKVwiXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

Front-end and server code is separate but both import the shared game definition.

**Comment by alexwoodsy** [comment]
@delucis thanks for your help.
Here is my server.js code 
`const {Server} = require("boardgame.io/server");
const {SHED} = require("./game");

const server = Server({ 
  games: [SHED],
 });

const lobbyConfig = {
    apiPort: 8080,
    apiCallback: () => console.log('Running Lobby API on port 8080...'),
  };

server.run({
    port: 8000,
    lobbyConfig,
}); `

I have tried removing the lobby config and I still get the same errors

**Comment by delucis** [comment]
@alexwoodsy That looks OK, but I’d guess the JSX code is somewhere inside `./game`. Is that possible?

**Comment by alexwoodsy** [comment]
Thanks you for the help @delucis, that was exactly the issue. I had imported/exported my board implementation into the `index.js` file in the `./game` folder I was using for my folder structure. 
thanks again for the help :)

**Comment by shamseen** [comment]
Hello! I am also having this issue but I don't have any JSX in my game definition ([gameSetup.js](https://github.com/shamseen/ludo-boardgame-js/blob/multiplayer/src/gameLogic/gameSetup.js)) , just the board ([gameView.js](https://github.com/shamseen/ludo-boardgame-js/blob/multiplayer/src/gameLogic/gameView.js)).

server code: 
```javascript
const { Server } = require('boardgame.io/server');
const { Ludo } = require('./src/gameLogic/gameSetup');

const server = Server({ games: [Ludo] });

server.run(8000);
```

game client:
```javascript
export const GameClient = Client(
    {
        game: Ludo, // game state
        board: GameView,
        numPlayers: 2,
        debug: true,
        multiplayer: SocketIO({ server: "localhost:8000" }),
    }
);
```

**Comment by delucis** [comment]
@shamseen Your game definition does import JSX (see [lines 1 and 3 in `gameSetup.js`](https://github.com/shamseen/ludo-boardgame-js/blob/77432dc055131d72fce0ee15a45b487c8607fa22/src/gameLogic/gameSetup.js#L1-L3)) even if you don’t have JSX in that file itself. That means that when the server imports `gameSetup.js`, it first evaluates the imports inside `gameSetup.js` and will pull in that JSX.

You’ll have to split the `Ludo` and `GameClient` exports into separate files.

**Comment by shamseen** [comment]
Thank you so much! It was driving me n u t s!

You guys have the best customer support
