### ISSUE TITLE
Can't force `endTurn` on early moves, with `moveLimit` > 1

### ISSUE THREAD

**Issue by samuelhwilliams** [boardgameio/boardgame.io#934]
To reproduce, create a game with this in its declaration:

```javascript
turn: 
{
  moveLimit: 2,
},
```

And then in a move, fire the endTurn event with the `force` argument:

```javascript
ctx.events.endTurn( { force: true } );
```

If you take this move as your first action, it just prints a debug message saying eg `INFO: cannot end turn before making 2 moves`. I'm not sure if `force` isn't properly propagating through the event, as in `flows.ts` it does seem to have logic to allow forcing the turn to end early.

For context, I'm trying to build a game where players have two actions by default, but one of those actions should immediately end the turn if taken first.

**Comment by delucis** [comment]
Hi! The `force` parameter isn’t actually exposed via the public `endTurn` event. The argument passed to `ctx.events.endTurn` is `arg` in the signature, with `force` being set internally to permit forcing the turn end when the phase ends:

https://github.com/boardgameio/boardgame.io/blob/b832b07be3191ac63cbf7d5387fe92c4577550e1/src/core/flow.ts#L478-L481

I’ve sometimes wondered whether `moveLimit` should be treated as just an upper limit rather than also creating a minimum number of moves, but that isn’t currently the case. (Perhaps even a `minMoves`/`maxMoves` API would be more flexible.)

For your use case, I would currently suggest not setting `moveLimit` and instead doing something like.

- action 1 that always ends the turn: `ctx.events.endTurn()`
- action 2 that ends the turn when taken second: `if (ctx.numMoves > 1) ctx.events.endTurn()`

**Comment by samuelhwilliams** [comment]
Noted, thanks 👍 

I haven't found anything that clearly defines what is exposed in `ctx` in one place - where's the best place to look that up? I ended up rolling my own action points tracker because I didn't read anything about `numMoves`. Good to know it exists though - thanks.

**Comment by delucis** [comment]
I don’t think `ctx` is documented in detail anywhere.

The most detailed source would probably be the Typescript interface although this doesn’t provide additional context or explanations.

https://github.com/boardgameio/boardgame.io/blob/c7f0fba16d61d7bfb3da081edb887e0d7623fcfa/src/types.ts#L51-L80

There’s a loose convention that fields prefixed with `_` are “private” as they are mostly metadata used internally.

For a better insight into what’s in `ctx` I’d recommend taking a look at the debug panel. This will show you all the “public” `ctx` fields and you can see how they change as you prototype. (For an example, check out [this Tic-Tac-Toe demo](https://codesandbox.io/s/bgio-plain-js-tutorial-ewyyt) although because it has `moveLimit: 1`, `numMoves` always displays as `0` in this case.)

**Comment by samuelhwilliams** [comment]
Very helpful, thank you 👍

**Comment by delucis** [comment]
A note here to say that in the short-term, we should stop blocking `endTurn` when a `moveLimit` is active. `moveLimit` would then literally be a limit on number of moves. If a user needed to enforce a minimum number of moves they would have to [disable the `endTurn` client event](https://boardgame.io/documentation/#/events?id=disabling-events).

Later we could explore renaming `moveLimit` to `maxMoves` and introduce a `minMoves` option. `{ minMoves: 2, maxMoves: 2 }` would then be equivalent to the current behaviour.

**Comment by senritsu** [comment]
As this was tagged "good first issue" I used this as an opportunity to get to know the codebase. 

The actual fix for the issue would have been really small (removing just one check and updating test), so I went a step further and tried adding the proposed `minMoves` option as well. `moveLimit` kept its name though, to prevent adding a breaking change.
