### ISSUE TITLE
multiplayer server path problem. 

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#938]
Framework adds port at the end of the server path. 

Here is my client : 

```
const GameClient = Client({
  game: Game,
  numPlayers: 100,
  board: myBoard,
  multiplayer: SocketIO({ server: "http://myaddress.com }),
});
```

Problem is that when client connect to server it adds port :80 at the end of url so i see error , because it tries to connect to 

`https://myadress.com:80/socket.io/?EIO=3&transport=polling&t=Nbw1IL5&b64=1`

instead of `https://myadress.com/socket.io/?EIO=3&transport=polling&t=Nbw1IL5&b64=1`. Can you explain me how come this port at the end and how to avoid this?

**Comment by pociej** [comment]
well my server is running on port 3020 ( bgio server ) and related nginx config is that : 

```
 location /socket.io/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;

                proxy_pass http://localhost:3020; 
``` 
Till last bgio.io version update ( will check which version exactly it was before) in my app it was working properly client was connecting to http://mysdress.com/socket.io. What is even stranger is that it depends on environment. Same built run on locale machine works ok, on DigitalOcean Deployment appears this problem. So up to above nginx config what should i set as assress? `mydomain:3020` ? then it tries to connect at `mydomain:3020/socket.io` which obviously doesnt work. So what to do ?

**Comment by pociej** [comment]
ssh was the reason, there should be https in address

**Comment by sridharraman** [comment]
Hi, related to this. The SocketIO server path works only if I give the port. It fails if I point a /location to the server. E.g.

This server path:
`multiplayer: SocketIO({ server: 'https://demos.mysite.in/gameserver' })`
doesn't work. It throws an error like this: `GET
https://demos.mysite.in/socket.io/?EIO=4&transport=polling&t=OVC6Kib
[HTTP/1.1 404 Not Found 28ms]`

It doesn't seem to go to the location /gameserver for the socket.io. Is that normal?

Instead, if I change the server path to this: `multiplayer: SocketIO({ server: 'http://demos.mysite.in:8000' }),`, where 8000 is the port where the server is running, it works fine with a caveat. Since the server is http, the client also needs to be http -- hence we need to disable security protection in the browser for this domain before making it work.

Is there a way I can get this to with https itself?

**Comment by sridharraman** [comment]
Hi, in case anyone is struggling with this, this is how I solved it.

So, having a sub-folder as the path to the server didn't work. I had another sub-domain `https://games.mysite.in` where the `location /` pointed to the socket.io server. The client was also in this same sub-domain under `https://games.mysite.in/play`. This worked fine.

One huge gotcha for me was due to using pm2 to run the game server. In the nginx config for the socket.io server, I kept giving the pm2 port where the app was running, while in fact I had to give the port where the server is running. Once I did that, it worked fine.
