### ISSUE TITLE
Sandbox code does not work

### ISSUE THREAD

**Issue by SliceOfBread** [boardgameio/boardgame.io#953]
The multiplayer code in the sandboxes https://codesandbox.io/s/bgio-plain-js-multiplayer-server-742oh and https://codesandbox.io/s/boardgameio-fsl8y do not work. The former at least lets you select a player but fails when you try to play. The latter just gets stuck "connecting...".

**Comment by bougattab** [comment]
I have the same issue with starting the tutorial and getting the following errors about credentials in the console if it could help:

ERROR: disallowed move: clickCell
ERROR: player not active - playerID=[1] - action[clickCell]
TypeError: Cannot destructure property 'credentials' of 'action.payload' as it is undefined.

**Comment by delucis** [comment]
@SliceOfBread The multiplayer CodeSandbox examples have to be downloaded and run locally as they need the multiplayer server running and CodeSandbox doesn’t let you run a custom server like that. In both examples, the errors are because the boardgame.io client tries and fails to connect to a server. (If you check the browser console, you’ll see errors where a connection to `localhost:8000` is failing.) Here are the relevant lines in the tutorial:

> To run the server, you can click **File** > **Export to ZIP** to download the project, then run the server and client as described above. Don’t forget to run `npm install` in the project directory first!

@bougattab Is this with the multiplayer tutorial? Are you using the CodeSandbox code or have you written your own by following the tutorial?

**Comment by SliceOfBread** [comment]
Thank you for clarifying this. I initially tried to do things locally but ran into a problem. I will try again fresh.
I suggest you clarify the docs to something like:
"This code cannot be run in the sandbox. To run the server, you can click...."

**Comment by SliceOfBread** [comment]
I'm not sure what I screwed up the first time but I got things to work. For posterity, here's what I did (I'm not sure all these steps are necessary).
Unzipped the multiplayer server sandbox file to a new directory.
In that directory:
npm init --yes
npm install boardgame.io
npm install --save-dev parcel-bundler
npm install esm
Re-unzipped package.json (I think all the unzipping could be done here?)
npm run serve

in another Terminal, switch to that same directory:
npm start
