### ISSUE TITLE
[question] endStage does not clear activePlayers

### ISSUE THREAD

**Issue by robinchm** [boardgameio/boardgame.io#964]
I am very new to this framework and just start experimenting it by implementing a very simple game.

node version: 14.17.3
boardgame.io version: 0.4.5

The game consists of two players taking turn to draw and play some cards. In each turn I defined two stages, in "draw" stage the player can draw some cards in which the stage ends by the move calling endStage(). This places the player in the "play" stage where the player plays some cards. In the move "playCard()", both endStage() and endTurn() are called.
```javascript
  turn: {
    onBegin: (G, ctx) => (ctx.events.setStage("draw")),
    stages: {
      draw: {
        moves: { drawCard },
        next: "play",
        endIf: G => (G.secret.deck.length <= 0),
      },
      play: {
        moves: { playCard },
      },
```

The behaviour I observed using the debug panel is that the 1st player goes through both stages without issue, but when the 2nd stage and turn end, `ctx.activePlayers` shows `{0: "draw"}`. While the stage correctly resets to "draw", the active player is incorrectly set to "0" while the currentPlayer is "1". The game is then stuck as no valid move is available.

I did not call `setActivePlayers` anywhere in my code, expecting by default that the active player should be set as the current player, or is that not the case?

===============

Somewhat a different question, does stage supports `start`option and `onBegin`/`onEnd` hooks? Tested them but they have no effect.

**Comment by delucis** [comment]
Hi @robinchm, here’s how you probably want to define this behaviour:

```js
  turn: {
    activePlayers: { currentPlayer: 'draw' },
    stages: {
      draw: {
        moves: { drawCard },
        next: "play",
      },
      play: {
        moves: { playCard },
      },
    },
  },
```

[The `activePlayers` option](https://boardgame.io/documentation/#/stages?id=configuring-active-players-at-the-beginning-of-a-turn) allows you to specify which players are in which stages at the beginning of the turn — like you are currently trying to do in `onBegin`.

The reason you get the wrong player using `endStage` is because currently all events (like `endStage`) use the player ID of the player who triggered the action, so in this case player 0 ends the turn and then the `endStage` event sets the stage for player 0 not player 1 even though the turn now belongs to player 1. This is pretty confusing, so it would be nice to improve that. 

You can see the full range of options in [the Game API reference](https://boardgame.io/documentation/#/api/Game). There is no `start` option (`activePlayers` is used instead) and `onBegin`/`onEnd` hooks are also not currently available (although they have been requested in #608).

**Comment by robinchm** [comment]
@delucis Thanks for the help! I tried setting the activePlayers as you suggested and it worked as expected.

I still don't understand the `endStage` and `endTurn` stuff. I call `endStage` before `endTurn` in the `playCard` move, which should guarantee that the current player is ending the stage first before he is ending the turn, and as the result the turn can be handed over to the other player. I think the only issue is the default behaviour when `activePlayers` is not set?

**Comment by delucis** [comment]
Where are you defining the loop? `G` being a proxy shouldn’t be an issue if you write your mutations inside moves etc., but you can’t access `G` outside of game logic except via the client. For example, the following kind of pattern won’t work.

```js
let externalG;

const game = {
  moves: {
    leakG: (G, ctx) => {
      externalG = G;
    },
  },
}

// Try using G after `leakG` move:
externalG // ~> expired proxy
```

**Comment by robinchm** [comment]
G is indeed only accessed inside the move. For example, my `playCard(G, ctx, card)` looks like the following (`playCard` is only invoked as a move in `play` stage):
```javascript
function playCard(G, ctx, card) {
  console.log(G.players.length) // undefined
  for (let i = 0; i < G.players.length; i++) {
    console.log(G.players[i].score)
  }
  ctx.events.endStage();
  ctx.events.endTurn();
}
```
The stage and turn advance correctly, but console logs `undefined` because `G.players` has no `length` attribute. Consequently, no player's score is logged since the loop can't be executed correctly.

**Comment by robinchm** [comment]
@delucis My bad, my state was not defined correctly (`players` is defined as an object as the chapter "secret state" shows, but I was looping over it like it is an array). Fixed the bug and everything is working as intended.

Really appreciate your patience and help!
