### ISSUE TITLE
Infinite loop detector not detecting infinite loop

### ISSUE THREAD

**Issue by vdfdev** [boardgameio/boardgame.io#979]
I was trying to upgrade FBG to the latest BGIO version, but the secret dracula bgio unit tests got into an infinite loop on this line:

https://github.com/freeboardgames/FreeBoardGames.org/blob/4ab6e45fb47849be212ce771b08a025a1d31b182/web/src/games/secretDracula/game.test.ts#L30

which is literally the first move the unit test executes. I got into the debugger and I found out that the code was looping through the check to detect infinite loops, but failing to detect it:

![image](https://user-images.githubusercontent.com/1034631/128977609-cb70137f-8693-4b23-b0e1-1bee4b089ff6.png)

`endedTurns` would always show up as 1, even though this was looping thousands of times.  Interesting too, I saw the `this.dispatch` to grow unbounded:

![image](https://user-images.githubusercontent.com/1034631/128977837-4907ed24-942a-42dc-bdc2-9d0c4f8c248f.png)

I started suspecting of this recent PR: https://github.com/boardgameio/boardgame.io/pull/957, so I downgraded to one release before it (v0.45.2) and the same test passes :).

Also, I spent several hours this weekend trying to debug why the mergers unit test was failing. In that case, it was failing in this line:

https://github.com/freeboardgames/FreeBoardGames.org/blob/4ab6e45fb47849be212ce771b08a025a1d31b182/web/src/games/mergers/game.test.ts#L1120

It seemed like this BGIO framework was ignoring this command to move to the correct stage:
https://github.com/freeboardgames/FreeBoardGames.org/blob/4ab6e45fb47849be212ce771b08a025a1d31b182/web/src/games/mergers/game.ts#L523

And interesting enough, at v0.45.2 it also passes! And at v0.46.0 it fails! I am not very familiar with the turn order/flow code to understand what is going on, and it is getting late here and I need to go to bed... But  tomorrow I will try to see if I can nail down the root cause. It seems very likely, however, that the PR #957 broke some code that it shouldn't.

**Comment by vdfdev** [comment]
@cristiands7 FYI

**Comment by delucis** [comment]
Definitely caused by #957. I suspect some of the change  in behaviour is intentional, but obviously the infinite loop isn’t.

### 1. Infinite loop

Seeing the unusual `setActivePlayers` calls in `phase.endIf` [in the Secret Dracula code](https://github.com/freeboardgames/FreeBoardGames.org/blob/4ab6e45fb47849be212ce771b08a025a1d31b182/web/src/games/secretDracula/phases/vote/phase.ts#L38-L56), I tried to make a reproduction:

https://codesandbox.io/s/boardgame-io-hooks-test-086ch?file=/src/Game.ts

The result surprised me, but it makes sense. Calling `setActivePlayers` from `endIf` triggers an infinite loop. This is because previously we didn’t run `endIf` checks after stage/active player events, which was annoying because you couldn’t end turns/phases in response to changes in the active players (like ending a turn when `activePlayers === null`). Now that we’ve enabled it, calling one of these events from `endIf` will cause infinite loops, because each `endIf` will trigger another `endIf`.

We should probably disable events entirely in the `endIf` triggers as they are not intended to be used for state mutations (very likely to be buggy given how often `endIf` triggers are run).

I’m not sure I 100% follow the Secret Dracula logic, but if this is being used to update active players each move, using the `onMove` hook might be more appropriate? Also, the `setActivePlayers` call in `phaseVotePriest.onBegin` will be ignored (see below).

### 2. Mergers bug

I think this is expected as we disabled `setStage`/`endStage`/`setActivePlayers` in `phase.onBegin`. Mergers and Secret Dracula were actually using this in a reliable way (using `setActivePlayers({ value })`), but these events were often buggy for most users because in `phase.onBegin` the *turn* hasn’t yet been updated, so `currentPlayer` for example is the current player of the last turn of the previous phase, and the player impacted by `setStage`/`endStage` is the player who took the action which ended the previous phase, not the new current player like many people expected.

Instead of `phase.onBegin`, you should use `phase.turn.onBegin`. If you really need active players setting only for the first turn in a phase, I guess something like the following pattern will work:

```js
phases: {
  A: {
    onBegin: (G) => {
      G.isPhaseBeginning = true;
    },
    turn: {
      onBegin: (G, ctx) => {
        if (G.isPhaseBeginning) {
          ctx.events.setActivePlayers({ value });
          G.isPhaseBeginning = false
        }
      },
    },
  },
},
```

**Comment by cristiands7** [comment]
> We should probably disable events entirely in the endIf triggers as they are not intended to be used for state mutations (very likely to be buggy given how often endIf triggers are run).

I agree with this.

**Comment by delucis** [comment]
Yeah, I wonder what the best approach is. We could kludge it and overwrite the event methods in the trigger wrapper:

https://github.com/boardgameio/boardgame.io/blob/bff1d29492858842a3c38c8c4dca72e2888dca73/src/core/flow.ts#L87-L92

But that would be pretty dirty. Perhaps plugins could declare a separate “trigger API”, which we attach instead. Then the events plugin could decide to provide each of its usual method names but they would log an error. Given this is quite a specific problem though, perhaps we just need a `noTriggers` flag in the plugin object, which if `true` means that plugin is not included in the enhanced `ctx` provided to triggers. In that case calling an event from `endIf` would simply throw an error because it doesn’t exist.

For the methods that are ignored (like in `phase.onBegin`), it should be relatively simple to add some logging each time we ignore them here: https://github.com/boardgameio/boardgame.io/blob/91cf25eb6325e43ba88ae09cc322366908515ee2/src/plugins/events/events.ts#L119-L142

I guess the tricky bit would just be how helpful we can make the error messages. (We probably won’t know which hook the event was called from, and there are several reasons why those cases can be triggered, like having `endTurn` called several times in a move, not only because the wrong hook was used.)

**Comment by cristiands7** [comment]
Maybe we can update the fnWrap function to know the type of hook being executed and attach it to the event information. In this way we could prevent the use of events on some hooks (showing an error message).

**Comment by delucis** [comment]
We only apply `fnWrap` [to moves](https://github.com/boardgameio/boardgame.io/blob/4efec1a1ad2f7d576a7ade35ced339aa530a9cfe/src/core/game.ts#L90-L90) and to hooks, not `endIf` ([compare `HookWrapper` and `TriggerWrapper`](https://github.com/boardgameio/boardgame.io/blob/bff1d29492858842a3c38c8c4dca72e2888dca73/src/core/flow.ts#L79-L92)), so I’m not sure if that would work in this case. Although it would be a much nicer experience if we could log something like “not supported in X hook” where appropriate.

**Comment by vdfdev** [comment]
Ok folks, I was able to migrate the secretDracula to the latest version, see this PR:
https://github.com/freeboardgames/FreeBoardGames.org/pull/921

However, I am still stuck on replicating the logic of mergers without the ability to set active players on the beginning of the phase (not turn):

https://github.com/freeboardgames/FreeBoardGames.org/blob/4ab6e45fb47849be212ce771b08a025a1d31b182/web/src/games/mergers/game.ts#L523

Because in this specific game, it  seems like if the user comes from another phase, they skip two stages. Any ideas on how to code this now? I guess I could somehow add some flag to the G to say it is the first turn/no moves were made, and only execute this on the first turn, but seems hacky since it was something that the framework used to support

... Also, after I am done with this, I will try to summarize these problems on the breaking changes of the CHANGELOG, so people upgrading bgio dont run into the same issue.

**Comment by vdfdev** [comment]
oh, I just re-read @delucis response and it seems like you suggested what I had in mind :P (using G as a hacky solution)
